import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans text-lg",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuickTech AI",
  description: "Generated by create next app",
  openGraph: {
    type: 'website',
    url: 'https://quicktech.vercel.app',
    siteName: 'QuickTech AI - YouTube',
    images: [
      {
        url: 'https://quicktech.vercel.app/og-image.png',
      },
    ],
    twitter: {
      card: 'summary_large_image',
      site: '@QuickTechAIPro',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
