import Script from 'next/script'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import ChatBot from "@/components/ChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans text-lg",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuickTech AI",
  description: "Generated by create next app",
  openGraph: {
    type: 'website',
    url: 'https://quicktech.vercel.app',
    siteName: 'QuickTech AI - YouTube',
    images: [
      {
        url: 'https://quicktech.vercel.app/og-image.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image' as const,
    site: '@QuickTechAIPro',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* Adsterra — instant approval, no AdSense needed */}
        <Script
          src="https://epnzryrk.com/act/files/tag.min.js"
          strategy="lazyOnload"
          data-cfasync="false"
        />
        {/* AdSense auto-ads — activates once approved */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4237294630161176"
          crossOrigin="anonymous"
          strategy="lazyOnload"
        />
        <Script
          src="http://31.97.56.148:3098/t.js"
          data-site="quicktechai.app"
          strategy="lazyOnload"
        />
        <ChatBot />
            <Script async src="http://31.97.56.148:3100/script.js" data-website-id="8dbfb240-466c-4e16-bd4b-a847141be237" strategy="afterInteractive" />
      </body>
    </html>
  );
}
